"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Gift } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { useAccount } from "@/features/auth/AccountProvider";
import { useTranslations } from "@/features/i18n/LocaleProvider";

interface ClaimResponse {
  ok: true;
  reward: { title: string; sponsor: string; emoji: string };
  couponCode: string;
  alreadyClaimed: boolean;
}

/**
 * Claiming a sponsor coupon.
 *
 * An ordinary coupon code, generated by the city app and shown at the counter. No token is
 * minted and nothing is transferred: the sponsor is rewarding verified behaviour, not buying
 * anything from anyone.
 */
export function ClaimRewardButton({
  rewardSlug,
  eligible,
  existingCode,
  requirement,
}: {
  rewardSlug: string;
  eligible: boolean;
  existingCode: string | null;
  requirement: string;
}) {
  const router = useRouter();
  const { status, signIn } = useAccount();
  const { t } = useTranslations();
  const [code, setCode] = useState<string | null>(existingCode);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (status !== "signed-in") {
    return (
      <Button variant="secondary" onClick={() => signIn()}>
        {t.auth.signInToCheck}
      </Button>
    );
  }

  if (code) {
    return (
      <div className="animate-pop rounded-2xl border-2 border-dashed border-sun-300 bg-sun-100/60 p-5 text-center">
        <p className="text-xs font-semibold tracking-wide text-sun-700 uppercase">
          {t.rewards.yourCoupon}
        </p>
        <p className="mt-2 font-mono text-2xl font-bold tracking-[0.15em] text-ink">{code}</p>
        <p className="mt-2 text-xs text-sun-700">{t.rewards.couponHint}</p>
      </div>
    );
  }

  if (!eligible) {
    return (
      <div className="rounded-2xl bg-paper-sunk p-4">
        <p className="text-sm font-semibold text-ink-soft">{t.rewards.notYet}</p>
        <p className="mt-1 text-sm text-ink-faint">{t.rewards.notYetBody(requirement)}</p>
      </div>
    );
  }

  async function claim() {
    setBusy(true);
    setError(null);
    try {
      const response = await fetch("/api/rewards/claim", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ rewardSlug }),
      });
      const data = (await response.json()) as ClaimResponse | { ok: false; error: string };
      if (!data.ok) throw new Error(data.error);
      setCode(data.couponCode);
      router.refresh();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : t.common.couldNotReach);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div>
      <Button onClick={claim} disabled={busy} className="gap-2">
        <Gift className="size-4" aria-hidden />
        {busy ? t.rewards.claiming : t.rewards.claim}
      </Button>
      {error ? <p className="mt-2 text-sm font-medium text-danger-700">{error}</p> : null}
    </div>
  );
}
